services:
  backend:
    build: ./server
    ports: ["8000:8000"]
    env_file: ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    build:
      context: ./client
      target: builder
    ports: ["5173:5173"]
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev -- --host
    environment:
      - VITE_API_URL=http://localhost:8000/api
