services:
  - type: web
    name: portfolio-backend
    runtime: python
    region: singapore
    plan: free
    pythonVersion: "3.12.9"
    rootDir: server
    buildCommand: |
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate
    startCommand: >
      gunicorn portfolio_backend.wsgi:application
      --bind 0.0.0.0:$PORT
      --workers 2
      --threads 2
      --access-logfile -
      --error-logfile -
    healthCheckPath: /api/health/
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: SECRET_KEY
        value: "4r1_9y*6z7-(^!&uf4(0uqrn_x9=$ry_ez$=w2id^%0!cfr866"
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_tuzfwE0J3jcB@ep-long-butterfly-a1ghl8yt.ap-southeast-1.aws.neon.tech/neondb?sslmode=require"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: RECIPIENT_EMAIL
        sync: false
      - key: PROD_CLIENT_URL
        value: https://aditya-s-tawde.vercel.app/
