services:
  - type: web
    name: portfolio-backend
    runtime: node
    region: singapore
    plan: free
    rootDir: server
    buildCommand: npm install && npm run build && npm run db:migrate && npm run db:seed
    startCommand: npm run start
    healthCheckPath: /api/health/
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: RECIPIENT_EMAIL
        sync: false
      - key: PROD_CLIENT_URL
        value: https://aditya-s-tawde.vercel.app
