# Generated by Django 6.0.1 on 2026-01-09 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_class', models.CharField(blank=True, help_text="FontAwesome or similar icon class, e.g., 'fab fa-react'", max_length=100)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tech Stack',
                'verbose_name_plural': 'Tech Stacks',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['-date_issued']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='certification',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='certification',
            old_name='logo',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='category',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='date',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='description',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='level',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='link',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='order',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='tech',
        ),
        migrations.AddField(
            model_name='certification',
            name='date_issued',
            field=models.DateField(default=datetime.date(2026, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certifications/'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='project',
            name='tech_stack',
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.ManyToManyField(blank=True, related_name='projects', to='portfolio.techstack'),
        ),
    ]
