# Generated by Django 6.0.1 on 2026-01-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_education_techstack_alter_certification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='image_url',
            field=models.URLField(blank=True, help_text='OR provide an external image URL (use this if not uploading)', null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a certificate image (any format: JPG, PNG, GIF, WebP, SVG, etc.)', null=True, upload_to='certifications/'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='url',
            field=models.URLField(blank=True, help_text='Link to verify/view the certificate', null=True),
        ),
    ]
