# Generated by Django 6.0.1 on 2026-01-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_certification_image_url_alter_certification_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='description',
            field=models.TextField(blank=True, help_text='Description of what you learned or achieved with this certification'),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('WEB', 'Web Development'), ('MOBILE', 'Mobile App'), ('AI_ML', 'AI/ML'), ('DATA', 'Data Science'), ('DESKTOP', 'Desktop App'), ('OTHER', 'Other')], default='WEB', help_text='Category for filtering projects', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, help_text='OR provide an external image URL (use this if not uploading)', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.ManyToManyField(blank=True, help_text='Select technologies used in this project', related_name='projects', to='portfolio.techstack'),
        ),
    ]
