# Generated by Django 6.0.1 on 2026-04-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_certification_description_project_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")],
                db_index=True,
                default="PUBLISHED",
                help_text="Draft projects won't appear on the frontend",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[
                    ("WEB", "Web Development"),
                    ("MOBILE", "Mobile App"),
                    ("AI_ML", "AI/ML"),
                    ("DATA", "Data Science"),
                    ("DESKTOP", "Desktop App"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                default="WEB",
                help_text="Category for filtering projects",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_featured",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
