# Generated by Django 6.0.1 on 2026-06-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_project_status_alter_project_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("hackathons", "Hackathons & Competitions"),
                            ("engineering", "Open Source & Self-Directed Engineering"),
                            ("academic", "Academic Projects"),
                            ("education", "Education"),
                        ],
                        db_index=True,
                        default="engineering",
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="🔬",
                        help_text="Emoji icon for this experience group",
                        max_length=10,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("purple", "Purple"),
                            ("cyan", "Cyan"),
                            ("green", "Green"),
                            ("pink", "Pink"),
                            ("orange", "Orange"),
                        ],
                        default="purple",
                        help_text="Dracula accent color for UI",
                        max_length=10,
                    ),
                ),
                (
                    "items",
                    models.JSONField(
                        default=list,
                        help_text='List of items: [{"name": "...", "date": "...", "detail": "..."}]',
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_visible", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Experience",
                "verbose_name_plural": "Experiences",
                "ordering": ["order"],
            },
        ),
    ]
